import { ParsedModule } from "../parsers/types.js";

/** A documentation gap found for one exported symbol in a changed file. */
export interface SymbolIssue {
  symbol: string;
  kind: "function" | "class" | "type";
  file: string;
  reasons: string[];
}

/** Result of a documentation-impact review over a set of changed modules. */
export interface ReviewResult {
  changedModules: number;
  exportedSymbols: number;
  referencedInDoc: number;
  issues: SymbolIssue[];
  ok: boolean;
}

/** Inputs for {@link reviewDocImpact}. */
export interface ReviewOptions {
  /** Full text of the documentation file being checked (may be empty). */
  docText: string;
  /** Display label for the doc, e.g. `README.md`. */
  docLabel: string;
  /** When true (default), also flag symbols with no inline doc comment. */
  requireInlineDoc?: boolean;
}

/** Returns true when `name` appears as a whole word anywhere in `docText`. */
function mentioned(docText: string, name: string): boolean {
  if (!docText) return false;
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`\\b${escaped}\\b`).test(docText);
}

/**
 * Reviews the documentation impact of a set of changed modules.
 *
 * For every exported top-level symbol (function, class, or type) in the changed
 * files, it checks two deterministic signals: whether the symbol is referenced
 * in the target documentation, and whether it has an inline doc comment. This
 * is the same AST-first, no-LLM approach as `aidoc score`, so it runs instantly
 * and is safe to gate CI on.
 */
export function reviewDocImpact(
  changedModules: ParsedModule[],
  opts: ReviewOptions,
): ReviewResult {
  const requireInline = opts.requireInlineDoc ?? true;
  const issues: SymbolIssue[] = [];
  let exportedSymbols = 0;
  let referencedInDoc = 0;

  const consider = (
    name: string,
    kind: SymbolIssue["kind"],
    file: string,
    doc: string | undefined,
  ): void => {
    exportedSymbols++;
    const reasons: string[] = [];

    if (mentioned(opts.docText, name)) {
      referencedInDoc++;
    } else {
      reasons.push(`not referenced in ${opts.docLabel}`);
    }

    if (requireInline && (!doc || !doc.trim())) {
      reasons.push("missing inline doc comment");
    }

    if (reasons.length > 0) {
      issues.push({ symbol: name, kind, file, reasons });
    }
  };

  for (const m of changedModules) {
    for (const f of m.functions) {
      if (f.isExported) consider(f.name, "function", m.filePath, f.existingDoc);
    }
    for (const c of m.classes) {
      if (c.isExported) consider(c.name, "class", m.filePath, c.existingDoc);
    }
    for (const t of m.types) {
      if (t.isExported) consider(t.name, "type", m.filePath, t.existingDoc);
    }
  }

  return {
    changedModules: changedModules.length,
    exportedSymbols,
    referencedInDoc,
    issues,
    ok: issues.length === 0,
  };
}

/** Renders a review result as a Markdown report (used for CLI output and PR comments). */
export function renderReviewMarkdown(result: ReviewResult): string {
  const lines: string[] = ["## 📝 aidoc documentation review", ""];

  if (result.changedModules === 0) {
    lines.push(
      "No changed source files to review. Documentation is unaffected.",
    );
    return lines.join("\n");
  }

  lines.push(
    `Reviewed **${result.exportedSymbols}** exported symbol(s) across ` +
      `**${result.changedModules}** changed file(s). ` +
      `${result.referencedInDoc} referenced in the docs.`,
    "",
  );

  if (result.ok) {
    lines.push("✅ No documentation gaps detected for the changed exports.");
    return lines.join("\n");
  }

  lines.push(
    `⚠️ **${result.issues.length}** exported symbol(s) may need documentation:`,
    "",
  );

  const byFile = new Map<string, SymbolIssue[]>();
  for (const issue of result.issues) {
    const list = byFile.get(issue.file) ?? [];
    list.push(issue);
    byFile.set(issue.file, list);
  }

  for (const [file, group] of byFile) {
    lines.push(`### \`${file}\``, "");
    for (const issue of group) {
      lines.push(
        `- **${issue.symbol}** (${issue.kind}) — ${issue.reasons.join("; ")}`,
      );
    }
    lines.push("");
  }

  lines.push(
    "> Generated by `aidoc review` — deterministic AST analysis, no LLM required.",
  );
  return lines.join("\n");
}
